### ISSUE TITLE
Web.Contents with the Content option is only supported when connecting anonymously

### ISSUE THREAD

**Issue by Felipe-UnB** [kerski/bringing-dataops-to-pbi#1]
Hi @kerski , how are you? I have been trying to connect your dashboard to my workspace but the GetTokenPPU is not working. Even though I set the connection to anonymous, it returns the following message. 

"An error occurred in the ‘GetTokenPPU’ query. DataSource.Error: Web.Contents with the Content option is only supported when connecting anonymously." 

Have you experienced something like this?

**Comment by kerski** [comment]
Apologies for the late reply.  In step 2 of the instructions, did you ignore the privacy levels and do not set any dropdown values?

If so, you may need to clear the cache https://support.biconnector.com/support/solutions/articles/8000072804-how-to-clear-cache-of-power-bi-desktop-
